services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    command: start-dev --import-realm
    env_file:
      - .env
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    volumes:
      - ./infra/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    ports:
      - "8080:8080"

  backend:
    build:
      context: .
      dockerfile: infra/docker/backend/Dockerfile
    working_dir: /app/backend
    command: /bin/sh /app/backend/entrypoint.sh
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DJANGO_DEBUG: "true"
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0,backend
      DJANGO_CSRF_TRUSTED_ORIGINS: http://localhost:4200,http://127.0.0.1:4200
    depends_on:
      - keycloak

  frontend:
    build:
      context: .
      dockerfile: infra/docker/frontend/Dockerfile
    depends_on:
      - backend
      - keycloak
    working_dir: /app/frontend
    command: npm start -- --poll 2000
    env_file:
      - .env
    volumes:
      - ./frontend:/app/frontend
      - frontend_node_modules:/app/frontend/node_modules
    ports:
      - "4200:4200"

volumes:
  frontend_node_modules:
